/** Dummy listing untuk demo halaman Landing dan Detail */
export const NEARBY_KOST_DUMMY = [
  {
    id: 'man1-1',
    title: 'Kost Gg. Melati Indah — dekat MAN 1 Bogor',
    area: 'Cibogor, Bogor Tengah',
    type: 'Kost Putri',
    roomsLeft: 2,
    priceLabel: 'Rp 1,8 Juta/bulan',
    minStay: 'Min. 3 bln (Rp 5,4 Juta)',
    photoCount: 8,
    owner: 'Ibu Siti',
    updated: 'Diperbarui 2 minggu lalu',
    seeds: ['man1a', 'man1b', 'man1c', 'man1d'],
  },
  {
    id: 'man1-2',
    title: 'Kost Nyaman Jl. Mayor Oking No. 12',
    area: 'Bogor Tengah, Kota Bogor',
    type: 'Kost Campur',
    roomsLeft: 4,
    priceLabel: 'Rp 2,1 Juta/bulan',
    minStay: 'Min. 6 bln (Rp 12,6 Juta)',
    photoCount: 6,
    owner: 'Pak Budi',
    updated: 'Diperbarui 5 hari lalu',
    seeds: ['man2a', 'man2b', 'man2c', 'man2d'],
  },
  {
    id: 'man1-3',
    title: 'Kost Elite Harmoni — 400 m dari MAN 1',
    area: 'Cibogor, Bogor Tengah',
    type: 'Kost Putra',
    roomsLeft: 1,
    priceLabel: 'Rp 2,5 Juta/bulan',
    minStay: 'Min. 6 bln (Rp 15 Juta)',
    photoCount: 10,
    owner: 'Kost Keluarga Raharjo',
    updated: 'Diperbarui 1 bulan lalu',
    seeds: ['man3a', 'man3b', 'man3c', 'man3d'],
  },
  {
    id: 'man1-4',
    title: 'Kost Bunda Asri — jalan kaki ke MAN 1',
    area: 'Gudang, Bogor Tengah',
    type: 'Kost Putri',
    roomsLeft: 3,
    priceLabel: 'Rp 1,5 Juta/bulan',
    minStay: 'Min. 3 bln (Rp 4,5 Juta)',
    photoCount: 5,
    owner: 'Bu Asri',
    updated: 'Diperbarui 3 hari lalu',
    seeds: ['man4a', 'man4b', 'man4c', 'man4d'],
  },
  {
    id: 'man1-5',
    title: 'Kost Simpel Cibogor — strategis ke MAN 1',
    area: 'Cibogor, Bogor Tengah',
    type: 'Kost Campur',
    roomsLeft: 5,
    priceLabel: 'Rp 1,2 Juta/bulan',
    minStay: 'Min. 1 bln',
    photoCount: 4,
    owner: 'Mas Rian',
    updated: 'Diperbarui 1 minggu lalu',
    seeds: ['man5a', 'man5b', 'man5c', 'man5d'],
  },
  {
    id: 'man1-6',
    title: 'Kost Hijau Asri Mayor Oking',
    area: 'Bogor Tengah, Kota Bogor',
    type: 'Kost Putri',
    roomsLeft: 2,
    priceLabel: 'Rp 2 Juta/bulan',
    minStay: 'Min. 6 bln (Rp 12 Juta)',
    photoCount: 7,
    owner: 'Ibu Lina',
    updated: 'Diperbarui 12 hari lalu',
    seeds: ['man6a', 'man6b', 'man6c', 'man6d'],
  },
]

export function getKostById(kostId) {
  return NEARBY_KOST_DUMMY.find((k) => k.id === kostId)
}

